version: "3"
networks: {}
volumes:
  bitcoin_datadir:
  lnd_datadir:
  tor_datadir:
  tor_torrcdir:
  tor_servicesdir:
services:
  bitcoind:
    links:
    - tor
    restart: unless-stopped
    container_name: playground-bitcoind
    build: 
      context: ./bitcoin-signet
      dockerfile: Dockerfile
    expose:
    - "38332"
    - "38333"
    - "38334"
    ports:
    - "38333:38333"
    volumes: 
    - "bitcoin_datadir:/root/.bitcoin/"   
  lnd:
    links:
    - bitcoind
    - tor
    restart: unless-stopped
    container_name: playground-lnd
    build: 
      context: ./lnd-signet
      dockerfile: Dockerfile
    expose:
    - "8080"
    - "9735"
    - "9911"
    - "10009"
    ports:
    - "8080:8080"
    - "9735:9735"
    - "9911:9911"
    - "10009:10009"
    volumes: 
    - "lnd_datadir:/root/.lnd/"
  tor:
      restart: unless-stopped
      container_name: playground-tor
      build:
        context: ./tor
        dockerfile: Dockerfile
      expose:
      - 9050
      - 9051
      ports:
      - "9050:9050"
      - "9051:9051"
      volumes: 
      - "tor_datadir:/home/tor/.tor"
      - "tor_torrcdir:/usr/local/etc/tor"
      - "tor_servicesdir:/var/lib/tor/hidden_services"