version: "3"
networks: {}
# volumes:
#   bitcoin_datadir:
#   lnd_datadir:
#   tor_datadir:
#   tor_torrcdir:
#   tor_servicesdir:
#   thub_datadir:
#   rtl_datadir:
services:
  bitcoind:
    links:
    - tor
    restart: unless-stopped
    container_name: playground-bitcoind
    build: 
      context: ./bitcoin-signet
      dockerfile: Dockerfile
    expose:
    - "38332"
    - "38333"
    - "38334"
    ports:
    - "38333:38333"
    volumes:
      - type: bind
        source: ${PWD}/volumes/bitcoin_datadir
        target: /root/.bitcoin/
  lnd:
    links:
    - bitcoind
    - tor
    restart: unless-stopped
    container_name: playground-lnd
    build: 
      context: ./lnd-signet
      dockerfile: Dockerfile
    expose:
    - "8080"
    - "9735"
    - "9911"
    - "10009"
    ports:
    - "8080:8080"
    - "9735:9735"
    - "9911:9911"
    - "10009:10009"
    volumes:
      - type: bind
        source: ${PWD}/volumes/lnd_datadir
        target: /root/.lnd/
  tor:
      restart: unless-stopped
      container_name: playground-tor
      build:
        context: ./tor
        dockerfile: Dockerfile
      expose:
      - 9050
      - 9051
      ports:
      - "9050:9050"
      - "9051:9051"
      volumes:
        - type: bind
          source: ${PWD}/volumes/tor_datadir
          target: /home/tor/.tor
        - type: bind
          source: ${PWD}/volumes/tor_torrcdir
          target: /usr/local/etc/tor
        - type: bind
          source: ${PWD}/volumes/tor_servicesdir
          target: /var/lib/tor/hidden_services
  thunderhub:
    container_name: playground-thub
    links: 
      - bitcoind
      - lnd
    build:
        context: ./thub
        dockerfile: Dockerfile
    restart: unless-stopped
    stop_signal: SIGKILL
    environment:
      NO_VERSION_CHECK: "true" 
      ACCOUNT_CONFIG_PATH: '/data/thubConfig.yaml'
      LOG_LEVEL: debug
    volumes:
      - type: bind
        source: ${PWD}/volumes/lnd_datadir
        target: /etc/lnd
      - type: bind
        source: ${PWD}/volumes/thub_datadir
        target: /data
    ports:
      - '3001:3000'  
  rtl:
      container_name: playground-rtl
      links: 
        - lnd      
        - bitcoind 
      restart: unless-stopped 
      environment: 
        LND_SERVER_URL: https://playground-lnd:8080/v1
        MACAROON_PATH: /root/.lnd/data/chain/bitcoin/signet
        RTL_CONFIG_PATH: /data/
        LND_CONFIG_PATH: /root/.lnd/lnd.conf
        BITCOIND_CONFIG_PATH: /etc/bitcoin/bitcoin.conf
        RTL_SSO: 0
        RTL_COOKIE_PATH: ''
        LOGOUT_REDIRECT_LINK: ''
        CONFIG_PATH: ''
        LN_IMPLEMENTATION: LND
      ports:
      - "3000:3000"
      image: shahanafarooqui/rtl:0.11.0 
      volumes:
        - type: bind
          source: ${PWD}/volumes/lnd_datadir
          target: /root/.lnd/
          read_only: true
        - type: bind
          source: ${PWD}/volumes/bitcoin_datadir
          target: /etc/bitcoin/
          read_only: true
        - type: bind
          source: ${PWD}/volumes/rtl_datadir
          target: /data
