version: "3"
networks: {}
volumes:
  bitcoin_datadir:
  lnd_datadir:
  tor_datadir:
  tor_torrcdir:
  tor_servicesdir:
  thub_datadir:
  rtl_datadir:
services:
  bitcoind:
    links:
    - tor
    restart: unless-stopped
    container_name: playground-bitcoind
    build: 
      context: ./bitcoin-signet
      dockerfile: Dockerfile
    expose:
    - "38332"
    - "38333"
    - "38334"
    ports:
    - "38333:38333"
    volumes: 
    - "bitcoin_datadir:/root/.bitcoin/"   
  lnd:
    links:
    - bitcoind
    - tor
    restart: unless-stopped
    container_name: playground-lnd
    build: 
      context: ./lnd-signet
      dockerfile: Dockerfile
    expose:
    - "8080"
    - "9735"
    - "9911"
    - "10009"
    ports:
    - "8080:8080"
    - "9735:9735"
    - "9911:9911"
    - "10009:10009"
    volumes: 
    - "lnd_datadir:/root/.lnd/"
  tor:
      restart: unless-stopped
      container_name: playground-tor
      build:
        context: ./tor
        dockerfile: Dockerfile
      expose:
      - 9050
      - 9051
      ports:
      - "9050:9050"
      - "9051:9051"
      volumes: 
      - "tor_datadir:/home/tor/.tor"
      - "tor_torrcdir:/usr/local/etc/tor"
      - "tor_servicesdir:/var/lib/tor/hidden_services"
  thunderhub:
    container_name: playground-thub
    links: 
      - bitcoind
      - lnd
    image: apotdevin/thunderhub:v0.12.24
    restart: unless-stopped
    stop_signal: SIGKILL
    environment:
      NO_VERSION_CHECK: "true" 
      ACCOUNT_CONFIG_PATH: '/data/thubConfig.yaml'
      LOG_LEVEL: debug
    volumes:
      - "lnd_datadir:/etc/lnd"
      - "thub_datadir:/data"
    ports:
      - '3000:3000'
    expose:
      - '3000'
    command: ['npm', 'run', 'start']
  rtl:
      container_name: playground-rtl
      links: 
        - lnd      
        - bitcoind 
      restart: unless-stopped 
      environment: 
        LND_SERVER_URL: https://playground-lnd:8080/v1
        MACAROON_PATH: /root/.lnd/data/chain/bitcoin/signet
        RTL_CONFIG_PATH: /data/
        LND_CONFIG_PATH: /root/.lnd/lnd.conf
        BITCOIND_CONFIG_PATH: /etc/bitcoin/bitcoin.conf
        RTL_SSO: 0
        RTL_COOKIE_PATH: ''
        LOGOUT_REDIRECT_LINK: ''
        CONFIG_PATH: ''
        LN_IMPLEMENTATION: LND
      ports:
      - "3000:3000"
      image: shahanafarooqui/rtl:0.11.0 
      volumes: 
      - lnd_datadir:/root/.lnd/:ro
      - bitcoin_datadir:/etc/bitcoin/:ro
      - rtl_datadir:/data
