name: plebnet-playground

# Controls when the action will run. 
on:
  pull_request:
    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #paths:
    #  - '.github/workflows/automate.yml'
    #schedule:
    #  - cron: "*/5 * * * *"
    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-workspace:
    name: github-workspace
    runs-on: ubuntu-18.04
    steps:
      - name: Print github workspace
        run: |
          printenv

  ubuntu-latest-build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: install, build, and test
        run: |
          sudo apt install python python3
          sudo apt install -y mkdocs
          pip install -r docs/requirements.txt
          pip install -r requirements.txt
          make init help report
          make build nocache=true
          make build para=true
          make install verbose=true
          #make uninstall

  ubuntu-20-build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: make init help report
        run: |
          make init help report
      - name: install, build, and test
        run: |
          sudo apt install python python3
          sudo apt install -y mkdocs
          pip install -r docs/requirements.txt
          pip install -r requirements.txt
          make build nocache=true
          make build para=true
          make install verbose=true
          #make uninstall
      - name: play
        run: |
          play
          play info
          play ids
      - name: bitcoind-commands
        run: |
          play bitcoin
          play bitcoin top
          play bitcoin restart &
          play bitcoin netinfo 5
          play bitcoin gettxoutsetinfo
          play bitcoin getmininginfo
          play bitcoin 'bitcoin-cli getblockhash 1000'
      - name: lnd-commands
        run: |
          # play defaults to the lnd container
          play lnd
          play lnd top
          play lnd restart &
          play lnd lncli
          play lncli
          play lncli --version
          play lnd 'lncli --version'

      - name: uninstall
        run: |
          make uninstall

